In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn import metrics
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [2]:
df=pd.read_csv('Breast_Cancer.csv')

In [3]:
df

Age   Race Marital Status T Stage  N Stage 6th Stage  \
0      68  White        Married       T1      N1       IIA   
1      50  White        Married       T2      N2      IIIA   
2      58  White       Divorced       T3      N3      IIIC   
3      58  White        Married       T1      N1       IIA   
4      47  White        Married       T2      N1       IIB   
...   ...    ...            ...      ...     ...       ...   
4019   62  Other        Married       T1      N1       IIA   
4020   56  White       Divorced       T2      N2      IIIA   
4021   68  White        Married       T2      N1       IIB   
4022   58  Black       Divorced       T2      N1       IIB   
4023   46  White        Married       T2      N1       IIB   

                  differentiate Grade   A Stage  Tumor Size Estrogen Status  \
0         Poorly differentiated     3  Regional           4        Positive   
1     Moderately differentiated     2  Regional          35        Positive   
2     Moderately differentiated     2  Regional          63        Positive   
3         Poorly differentiated     3  Regional          18        Positive   
4         Poorly differentiated     3  Regional          41        Positive   
...                         ...   ...       ...         ...             ...   
4019  Moderately differentiated     2  Regional           9        Positive   
4020  Moderately differentiated     2  Regional          46        Positive   
4021  Moderately differentiated     2  Regional          22        Positive   
4022  Moderately differentiated     2  Regional          44        Positive   
4023  Moderately differentiated     2  Regional          30        Positive   

     Progesterone Status  Regional Node Examined  Reginol Node Positive  \
0               Positive                      24                      1   
1               Positive                      14                      5   
2               Positive                      14                      7   
3               Positive                       2                      1   
4               Positive                       3                      1   
...                  ...                     ...                    ...   
4019            Positive                       1                      1   
4020            Positive                      14                      8   
4021            Negative                      11                      3   
4022            Positive                      11                      1   
4023            Positive                       7                      2   

      Survival Months Status  
0                  60  Alive  
1                  62  Alive  
2                  75  Alive  
3                  84  Alive  
4                  50  Alive  
...               ...    ...  
4019               49  Alive  
4020               69  Alive  
4021               69  Alive  
4022               72  Alive  
4023              100  Alive  

[4024 rows x 16 columns]

In [4]:
df.head()

Age   Race Marital Status T Stage  N Stage 6th Stage  \
0   68  White        Married       T1      N1       IIA   
1   50  White        Married       T2      N2      IIIA   
2   58  White       Divorced       T3      N3      IIIC   
3   58  White        Married       T1      N1       IIA   
4   47  White        Married       T2      N1       IIB   

               differentiate Grade   A Stage  Tumor Size Estrogen Status  \
0      Poorly differentiated     3  Regional           4        Positive   
1  Moderately differentiated     2  Regional          35        Positive   
2  Moderately differentiated     2  Regional          63        Positive   
3      Poorly differentiated     3  Regional          18        Positive   
4      Poorly differentiated     3  Regional          41        Positive   

  Progesterone Status  Regional Node Examined  Reginol Node Positive  \
0            Positive                      24                      1   
1            Positive                      14                      5   
2            Positive                      14                      7   
3            Positive                       2                      1   
4            Positive                       3                      1   

   Survival Months Status  
0               60  Alive  
1               62  Alive  
2               75  Alive  
3               84  Alive  
4               50  Alive

In [5]:
df.tail()

Age   Race Marital Status T Stage  N Stage 6th Stage  \
4019   62  Other        Married       T1      N1       IIA   
4020   56  White       Divorced       T2      N2      IIIA   
4021   68  White        Married       T2      N1       IIB   
4022   58  Black       Divorced       T2      N1       IIB   
4023   46  White        Married       T2      N1       IIB   

                  differentiate Grade   A Stage  Tumor Size Estrogen Status  \
4019  Moderately differentiated     2  Regional           9        Positive   
4020  Moderately differentiated     2  Regional          46        Positive   
4021  Moderately differentiated     2  Regional          22        Positive   
4022  Moderately differentiated     2  Regional          44        Positive   
4023  Moderately differentiated     2  Regional          30        Positive   

     Progesterone Status  Regional Node Examined  Reginol Node Positive  \
4019            Positive                       1                      1   
4020            Positive                      14                      8   
4021            Negative                      11                      3   
4022            Positive                      11                      1   
4023            Positive                       7                      2   

      Survival Months Status  
4019               49  Alive  
4020               69  Alive  
4021               69  Alive  
4022               72  Alive  
4023              100  Alive

In [6]:
df.columns

Index(['Age', 'Race', 'Marital Status', 'T Stage ', 'N Stage', '6th Stage',
       'differentiate', 'Grade', 'A Stage', 'Tumor Size', 'Estrogen Status',
       'Progesterone Status', 'Regional Node Examined',
       'Reginol Node Positive', 'Survival Months', 'Status'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4024 entries, 0 to 4023
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Age                     4024 non-null   int64 
 1   Race                    4024 non-null   object
 2   Marital Status          4024 non-null   object
 3   T Stage                 4024 non-null   object
 4   N Stage                 4024 non-null   object
 5   6th Stage               4024 non-null   object
 6   differentiate           4024 non-null   object
 7   Grade                   4024 non-null   object
 8   A Stage                 4024 non-null   object
 9   Tumor Size              4024 non-null   int64 
 10  Estrogen Status         4024 non-null   object
 11  Progesterone Status     4024 non-null   object
 12  Regional Node Examined  4024 non-null   int64 
 13  Reginol Node Positive   4024 non-null   int64 
 14  Survival Months         4024 non-null   int64 
 15  Stat

In [8]:
df['Race'].unique()

array(['White', 'Black', 'Other'], dtype=object)

In [9]:
df['Marital Status'].unique()

array(['Married', 'Divorced', 'Single ', 'Widowed', 'Separated'],
      dtype=object)

In [10]:
df['differentiate'].unique()

array(['Poorly differentiated', 'Moderately differentiated',
       'Well differentiated', 'Undifferentiated'], dtype=object)

In [11]:
df['Grade'].unique()

array(['3', '2', '1', ' anaplastic; Grade IV'], dtype=object)

In [12]:
df['A Stage'].unique()

array(['Regional', 'Distant'], dtype=object)

In [13]:
df['Estrogen Status'].unique()

array(['Positive', 'Negative'], dtype=object)

In [14]:
df['Progesterone Status'].unique()

array(['Positive', 'Negative'], dtype=object)

In [15]:
df['T Stage '].unique()

array(['T1', 'T2', 'T3', 'T4'], dtype=object)

In [16]:
df['N Stage'].unique()

array(['N1', 'N2', 'N3'], dtype=object)

In [17]:
df['6th Stage'].unique()

array(['IIA', 'IIIA', 'IIIC', 'IIB', 'IIIB'], dtype=object)

In [18]:
df['Status'].unique()

array(['Alive', 'Dead'], dtype=object)

In [19]:
df['Race']=df['Race'].replace(to_replace=['White','Black','Other'],value=[0,1,2])

C:\Users\Admin\AppData\Local\Temp\ipykernel_1312\911296819.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Race']=df['Race'].replace(to_replace=['White','Black','Other'],value=[0,1,2])


In [20]:
df['Marital Status']=df['Marital Status'].replace(to_replace=['Married', 'Divorced', 'Single ', 'Widowed', 'Separated'],value=[0,1,2,3,4])

C:\Users\Admin\AppData\Local\Temp\ipykernel_1312\2111894598.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Marital Status']=df['Marital Status'].replace(to_replace=['Married', 'Divorced', 'Single ', 'Widowed', 'Separated'],value=[0,1,2,3,4])


In [21]:
df['differentiate']=df['differentiate'].replace(to_replace=['Poorly differentiated', 'Moderately differentiated',
       'Well differentiated', 'Undifferentiated'],value=[0,1,2,3])

C:\Users\Admin\AppData\Local\Temp\ipykernel_1312\4089587089.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['differentiate']=df['differentiate'].replace(to_replace=['Poorly differentiated', 'Moderately differentiated',


In [22]:
df['Grade']=df['Grade'].replace(to_replace=['anaplastic; Grade IV'],value=[0])

In [23]:
df['A Stage']=df['A Stage'].replace(to_replace=['Regional', 'Distant'],value=[0,1])

C:\Users\Admin\AppData\Local\Temp\ipykernel_1312\356706312.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['A Stage']=df['A Stage'].replace(to_replace=['Regional', 'Distant'],value=[0,1])


In [24]:
df['Estrogen Status']=df['Estrogen Status'].replace(to_replace=['Positive', 'Negative'],value=[0,1])

C:\Users\Admin\AppData\Local\Temp\ipykernel_1312\1671093037.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Estrogen Status']=df['Estrogen Status'].replace(to_replace=['Positive', 'Negative'],value=[0,1])


In [25]:
df['Progesterone Status']=df['Progesterone Status'].replace(to_replace=['Positive', 'Negative'],value=[0,1])

C:\Users\Admin\AppData\Local\Temp\ipykernel_1312\867792333.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Progesterone Status']=df['Progesterone Status'].replace(to_replace=['Positive', 'Negative'],value=[0,1])


In [26]:
df['Status']=df['Status'].replace(to_replace=['Alive', 'Dead'],value=[0,1])

C:\Users\Admin\AppData\Local\Temp\ipykernel_1312\2601964553.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Status']=df['Status'].replace(to_replace=['Alive', 'Dead'],value=[0,1])


In [27]:
le=LabelEncoder()
for column in df.columns:
    if df[column].dtypes=='object':
        df[column]=le.fit_transform(df[column])

In [28]:
df

Age  Race  Marital Status  T Stage   N Stage  6th Stage  differentiate  \
0      68     0               0         0        0          0              0   
1      50     0               0         1        1          2              1   
2      58     0               1         2        2          4              1   
3      58     0               0         0        0          0              0   
4      47     0               0         1        0          1              0   
...   ...   ...             ...       ...      ...        ...            ...   
4019   62     2               0         0        0          0              1   
4020   56     0               1         1        1          2              1   
4021   68     0               0         1        0          1              1   
4022   58     1               1         1        0          1              1   
4023   46     0               0         1        0          1              1   

      Grade  A Stage  Tumor Size  Estrogen Status  Progesterone Status  \
0         3        0           4                0                    0   
1         2        0          35                0                    0   
2         2        0          63                0                    0   
3         3        0          18                0                    0   
4         3        0          41                0                    0   
...     ...      ...         ...              ...                  ...   
4019      2        0           9                0                    0   
4020      2        0          46                0                    0   
4021      2        0          22                0                    1   
4022      2        0          44                0                    0   
4023      2        0          30                0                    0   

      Regional Node Examined  Reginol Node Positive  Survival Months  Status  
0                         24                      1               60       0  
1                         14                      5               62       0  
2                         14                      7               75       0  
3                          2                      1               84       0  
4                          3                      1               50       0  
...                      ...                    ...              ...     ...  
4019                       1                      1               49       0  
4020                      14                      8               69       0  
4021                      11                      3               69       0  
4022                      11                      1               72       0  
4023                       7                      2              100       0  

[4024 rows x 16 columns]

In [29]:
X=df.drop(columns='Status')
Y=df['Status']

In [30]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=42,test_size=0.2)

In [31]:
model1=LogisticRegression()
model1.fit(X_train,Y_train)

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [32]:
Y_predict1=model1.predict(X_test)
Y_predict1

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [33]:
accuracy=accuracy_score(Y_test,Y_predict1)
accuracy

0.901863354037267

In [34]:
cm=confusion_matrix(Y_test,Y_predict1)
cm

array([[671,  14],
       [ 65,  55]], dtype=int64)

In [35]:
precision=metrics.precision_score(Y_test,Y_predict1)
precision

0.7971014492753623

In [36]:
sensitivity_recall=metrics.recall_score(Y_test,Y_predict1)
sensitivity_recall

0.4583333333333333

In [37]:
f1_score=metrics.f1_score(Y_test,Y_predict1)
f1_score


0.582010582010582

In [38]:
cr=classification_report(Y_test,Y_predict1)
print(cr)

              precision    recall  f1-score   support

           0       0.91      0.98      0.94       685
           1       0.80      0.46      0.58       120

    accuracy                           0.90       805
   macro avg       0.85      0.72      0.76       805
weighted avg       0.89      0.90      0.89       805



In [39]:
model2=DecisionTreeClassifier()
model2.fit(X_train,Y_train)

DecisionTreeClassifier()

In [40]:
Y_pred=model2.predict(X_test)
Y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [41]:
accy=accuracy_score(Y_test,Y_pred)
accy

0.8658385093167702

In [42]:
cm2=confusion_matrix(Y_test,Y_pred)
cm2

array([[630,  55],
       [ 53,  67]], dtype=int64)

In [43]:
prn=metrics.precision_score(Y_test,Y_pred)
prn

0.5491803278688525

In [44]:
senrecal=metrics.recall_score(Y_test,Y_pred)
senrecal

0.5583333333333333

In [45]:
f1_score2=metrics.f1_score(Y_test,Y_pred)
f1_score2


0.5537190082644629

In [46]:
cr2=classification_report(Y_test,Y_pred)
print(cr2)

              precision    recall  f1-score   support

           0       0.92      0.92      0.92       685
           1       0.55      0.56      0.55       120

    accuracy                           0.87       805
   macro avg       0.74      0.74      0.74       805
weighted avg       0.87      0.87      0.87       805



In [47]:
model3=SVC()
model3.fit(X_train,Y_train)

SVC()

In [48]:
Y_pred3=model3.predict(X_test)
Y_pred3

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [49]:
cm3=confusion_matrix(Y_test,Y_pred3)
cm3

array([[676,   9],
       [ 76,  44]], dtype=int64)

In [50]:
cr3=classification_report(Y_test,Y_pred3)
print(cr3)

              precision    recall  f1-score   support

           0       0.90      0.99      0.94       685
           1       0.83      0.37      0.51       120

    accuracy                           0.89       805
   macro avg       0.86      0.68      0.72       805
weighted avg       0.89      0.89      0.88       805



In [51]:
accy=accuracy_score(Y_test,Y_pred3)
accy

0.8944099378881988

In [52]:
prn=metrics.precision_score(Y_test,Y_pred3)
prn

0.8301886792452831

In [53]:
senrecal=metrics.recall_score(Y_test,Y_pred3)
senrecal

0.36666666666666664

In [54]:
f1_score3=metrics.f1_score(Y_test,Y_pred3)
f1_score3

0.5086705202312138

In [55]:
model4=RandomForestClassifier()
model4.fit(X_train,Y_train)

RandomForestClassifier()

In [56]:
Y_pred4=model4.predict(X_test)
Y_pred4

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [57]:
cm=confusion_matrix(Y_test,Y_pred4)
cm

array([[675,  10],
       [ 59,  61]], dtype=int64)

In [58]:
cr=classification_report(Y_test,Y_pred4)
print(cr)

              precision    recall  f1-score   support

           0       0.92      0.99      0.95       685
           1       0.86      0.51      0.64       120

    accuracy                           0.91       805
   macro avg       0.89      0.75      0.80       805
weighted avg       0.91      0.91      0.90       805



In [59]:
accuracy=accuracy_score(Y_test,Y_pred4)*100
precision=metrics.precision_score(Y_test,Y_pred4)*100
semsitivity_recall=metrics.recall_score(Y_test,Y_pred4)*100
f1_score=metrics.f1_score(Y_test,Y_pred4)*100
print('accuracy:',accuracy)
print('precision:',precision)
print('semsitivity_recall:',semsitivity_recall)
print('f1_score:',f1_score)

accuracy: 91.42857142857143
precision: 85.91549295774648
semsitivity_recall: 50.83333333333333
f1_score: 63.87434554973822
