In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor

In [2]:
df=pd.read_csv('C:/Users/Admin/Downloads/.ipynb_checkpoints/Electricity_Price_Prediction-checkpoint.csv')

In [3]:
df

DateTime         Holiday  HolidayFlag  DayOfWeek  WeekOfYear  \
0      01-11-2011 00:00             NaN            0          1          44   
1      01-11-2011 00:30             NaN            0          1          44   
2      01-11-2011 01:00             NaN            0          1          44   
3      01-11-2011 01:30             NaN            0          1          44   
4      01-11-2011 02:00             NaN            0          1          44   
...                 ...             ...          ...        ...         ...   
38009  31-12-2013 21:30  New Year's Eve            1          1           1   
38010  31-12-2013 22:00  New Year's Eve            1          1           1   
38011  31-12-2013 22:30  New Year's Eve            1          1           1   
38012  31-12-2013 23:00  New Year's Eve            1          1           1   
38013  31-12-2013 23:30  New Year's Eve            1          1           1   

       Day  Month  Year  PeriodOfDay  ForecastWindProduction  SystemLoadEA  \
0        1     11  2011            0                  315.31       3388.77   
1        1     11  2011            1                  321.80       3196.66   
2        1     11  2011            2                  328.57       3060.71   
3        1     11  2011            3                  335.60       2945.56   
4        1     11  2011            4                  342.90       2849.34   
...    ...    ...   ...          ...                     ...           ...   
38009   31     12  2013           43                 1179.14       3932.22   
38010   31     12  2013           44                 1152.01       3821.44   
38011   31     12  2013           45                 1123.67       3724.21   
38012   31     12  2013           46                 1094.24       3638.16   
38013   31     12  2013           47                 1064.00       3624.25   

       SMPEA ORKTemperature ORKWindspeed  CO2Intensity  ActualWindProduction  \
0      49.26           6.00         9.30        600.71                 356.0   
1      49.26           6.00        11.10        605.42                 317.0   
2      49.10           5.00        11.10        589.97                 311.0   
3      48.04           6.00         9.30        585.94                 313.0   
4      33.75           6.00        11.10        571.52                 346.0   
...      ...            ...          ...           ...                   ...   
38009  34.51           6.00        22.20        285.31                 812.0   
38010  33.83           5.00        24.10        278.31                 852.0   
38011  31.75           4.00        20.40        280.91                 962.0   
38012  33.83           5.00        14.80        302.46                 950.0   
38013  33.83           5.00        16.70        308.01                1020.0   

       SystemLoadEP2  SMPEP2  
0            3159.60   54.32  
1            2973.01   54.23  
2            2834.00   54.23  
3            2725.99   53.47  
4            2655.64   39.87  
...              ...     ...  
38009        3692.95   42.45  
38010        3571.00   33.83  
38011        3460.29   31.75  
38012        3563.99   50.60  
38013        3517.08   34.90  

[38014 rows x 18 columns]

In [4]:
df.head()

DateTime Holiday  HolidayFlag  DayOfWeek  WeekOfYear  Day  Month  \
0  01-11-2011 00:00     NaN            0          1          44    1     11   
1  01-11-2011 00:30     NaN            0          1          44    1     11   
2  01-11-2011 01:00     NaN            0          1          44    1     11   
3  01-11-2011 01:30     NaN            0          1          44    1     11   
4  01-11-2011 02:00     NaN            0          1          44    1     11   

   Year  PeriodOfDay  ForecastWindProduction  SystemLoadEA  SMPEA  \
0  2011            0                  315.31       3388.77  49.26   
1  2011            1                  321.80       3196.66  49.26   
2  2011            2                  328.57       3060.71  49.10   
3  2011            3                  335.60       2945.56  48.04   
4  2011            4                  342.90       2849.34  33.75   

  ORKTemperature ORKWindspeed  CO2Intensity  ActualWindProduction  \
0           6.00         9.30        600.71                 356.0   
1           6.00        11.10        605.42                 317.0   
2           5.00        11.10        589.97                 311.0   
3           6.00         9.30        585.94                 313.0   
4           6.00        11.10        571.52                 346.0   

   SystemLoadEP2  SMPEP2  
0        3159.60   54.32  
1        2973.01   54.23  
2        2834.00   54.23  
3        2725.99   53.47  
4        2655.64   39.87

In [5]:
df.tail()

DateTime         Holiday  HolidayFlag  DayOfWeek  WeekOfYear  \
38009  31-12-2013 21:30  New Year's Eve            1          1           1   
38010  31-12-2013 22:00  New Year's Eve            1          1           1   
38011  31-12-2013 22:30  New Year's Eve            1          1           1   
38012  31-12-2013 23:00  New Year's Eve            1          1           1   
38013  31-12-2013 23:30  New Year's Eve            1          1           1   

       Day  Month  Year  PeriodOfDay  ForecastWindProduction  SystemLoadEA  \
38009   31     12  2013           43                 1179.14       3932.22   
38010   31     12  2013           44                 1152.01       3821.44   
38011   31     12  2013           45                 1123.67       3724.21   
38012   31     12  2013           46                 1094.24       3638.16   
38013   31     12  2013           47                 1064.00       3624.25   

       SMPEA ORKTemperature ORKWindspeed  CO2Intensity  ActualWindProduction  \
38009  34.51           6.00        22.20        285.31                 812.0   
38010  33.83           5.00        24.10        278.31                 852.0   
38011  31.75           4.00        20.40        280.91                 962.0   
38012  33.83           5.00        14.80        302.46                 950.0   
38013  33.83           5.00        16.70        308.01                1020.0   

       SystemLoadEP2  SMPEP2  
38009        3692.95   42.45  
38010        3571.00   33.83  
38011        3460.29   31.75  
38012        3563.99   50.60  
38013        3517.08   34.90

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38014 entries, 0 to 38013
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   DateTime                38014 non-null  object 
 1   Holiday                 1536 non-null   object 
 2   HolidayFlag             38014 non-null  int64  
 3   DayOfWeek               38014 non-null  int64  
 4   WeekOfYear              38014 non-null  int64  
 5   Day                     38014 non-null  int64  
 6   Month                   38014 non-null  int64  
 7   Year                    38014 non-null  int64  
 8   PeriodOfDay             38014 non-null  int64  
 9   ForecastWindProduction  38009 non-null  float64
 10  SystemLoadEA            38012 non-null  float64
 11  SMPEA                   38012 non-null  float64
 12  ORKTemperature          38014 non-null  object 
 13  ORKWindspeed            38014 non-null  object 
 14  CO2Intensity            38007 non-null

In [7]:
df1=df.drop(columns=['DateTime','Holiday','HolidayFlag','DayOfWeek','WeekOfYear','PeriodOfDay'])

In [8]:
df1

Day  Month  Year  ForecastWindProduction  SystemLoadEA  SMPEA  \
0        1     11  2011                  315.31       3388.77  49.26   
1        1     11  2011                  321.80       3196.66  49.26   
2        1     11  2011                  328.57       3060.71  49.10   
3        1     11  2011                  335.60       2945.56  48.04   
4        1     11  2011                  342.90       2849.34  33.75   
...    ...    ...   ...                     ...           ...    ...   
38009   31     12  2013                 1179.14       3932.22  34.51   
38010   31     12  2013                 1152.01       3821.44  33.83   
38011   31     12  2013                 1123.67       3724.21  31.75   
38012   31     12  2013                 1094.24       3638.16  33.83   
38013   31     12  2013                 1064.00       3624.25  33.83   

      ORKTemperature ORKWindspeed  CO2Intensity  ActualWindProduction  \
0               6.00         9.30        600.71                 356.0   
1               6.00        11.10        605.42                 317.0   
2               5.00        11.10        589.97                 311.0   
3               6.00         9.30        585.94                 313.0   
4               6.00        11.10        571.52                 346.0   
...              ...          ...           ...                   ...   
38009           6.00        22.20        285.31                 812.0   
38010           5.00        24.10        278.31                 852.0   
38011           4.00        20.40        280.91                 962.0   
38012           5.00        14.80        302.46                 950.0   
38013           5.00        16.70        308.01                1020.0   

       SystemLoadEP2  SMPEP2  
0            3159.60   54.32  
1            2973.01   54.23  
2            2834.00   54.23  
3            2725.99   53.47  
4            2655.64   39.87  
...              ...     ...  
38009        3692.95   42.45  
38010        3571.00   33.83  
38011        3460.29   31.75  
38012        3563.99   50.60  
38013        3517.08   34.90  

[38014 rows x 12 columns]

In [9]:
df1.isnull().sum()

Day                       0
Month                     0
Year                      0
ForecastWindProduction    5
SystemLoadEA              2
SMPEA                     2
ORKTemperature            0
ORKWindspeed              0
CO2Intensity              7
ActualWindProduction      5
SystemLoadEP2             2
SMPEP2                    2
dtype: int64

In [10]:
df1['ForecastWindProduction']=df1['ForecastWindProduction'].fillna(df1['ForecastWindProduction'].mean())

In [11]:
df1['SystemLoadEA']=df1['SystemLoadEA'].fillna(df1['SystemLoadEA'].mean())

In [12]:
df1['SMPEA']=df1['SMPEA'].fillna(df1['SMPEA'].mean())

In [13]:
df1['CO2Intensity']=df1['CO2Intensity'].fillna(df1['CO2Intensity'].mean())

In [14]:
df1['ActualWindProduction']=df1['ActualWindProduction'].fillna(df1['ActualWindProduction'].mean())

In [15]:
df1['SystemLoadEP2']=df1['SystemLoadEP2'].fillna(df1['SystemLoadEP2'].mean())

In [16]:
df1['SMPEP2']=df1['SMPEP2'].fillna(df1['SMPEP2'].mean())

In [17]:
df1.dtypes

Day                         int64
Month                       int64
Year                        int64
ForecastWindProduction    float64
SystemLoadEA              float64
SMPEA                     float64
ORKTemperature             object
ORKWindspeed               object
CO2Intensity              float64
ActualWindProduction      float64
SystemLoadEP2             float64
SMPEP2                    float64
dtype: object

In [18]:
df1['ORKTemperature'] = pd.to_numeric(df1['ORKTemperature'], errors='coerce')

In [19]:
# Compute the mean while skipping NaN
mean_temp = df1['ORKTemperature'].mean()

# Fill missing values
df1['ORKTemperature'] = df1['ORKTemperature'].fillna(mean_temp)

In [20]:
df1['ORKWindspeed'] = pd.to_numeric(df1['ORKWindspeed'], errors='coerce')
mean_wind = df1['ORKWindspeed'].mean()
df1['ORKWindspeed'] = df1['ORKWindspeed'].fillna(mean_wind)

In [21]:
LE=LabelEncoder()

In [22]:
for column in df.columns:
        if df[column].dtype == 'object':
            df[column] = LE.fit_transform(df[column])

In [23]:
df1.dtypes

Day                         int64
Month                       int64
Year                        int64
ForecastWindProduction    float64
SystemLoadEA              float64
SMPEA                     float64
ORKTemperature            float64
ORKWindspeed              float64
CO2Intensity              float64
ActualWindProduction      float64
SystemLoadEP2             float64
SMPEP2                    float64
dtype: object

In [24]:
X= df1.drop(columns='ActualWindProduction')
y= df1['ActualWindProduction']

In [25]:
X_train , X_test , y_train , y_test = train_test_split( X,y,random_state=42,test_size=0.2)

In [26]:

model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [27]:
y_predict = model.predict(X_test)
y_predict

array([528.86437801, 101.47486975,  87.96931735, ..., 805.513269  ,
       439.7358213 , 311.56845137])

In [28]:
mse=mean_squared_error(y_test,y_predict)
mse

11500.109057738442

In [29]:
rmse=np.sqrt(mse)
rmse

107.23856143075793

In [30]:
rss=np.sum(np.square(y_test-y_predict))
rss

87435329.16598538

In [31]:
mae=mean_absolute_error(y_test,y_predict)
mae

80.17558274808036

In [32]:
r2_error=r2_score(y_test,y_predict)
r2_error

0.9192469429762851

In [33]:
model2=DecisionTreeRegressor()
model2.fit(X_train,y_train)

DecisionTreeRegressor()

In [34]:
y_pred=model2.predict(X_test)
y_pred

array([566.,  85.,  33., ..., 532., 566., 293.])

In [35]:
mse=mean_squared_error(y_test,y_pred)
mse

9689.074575825332

In [36]:
mae=mean_absolute_error(y_test,y_pred)
mae

64.64448244114165

In [37]:
r2_error=r2_score(y_test,y_pred)
r2_error

0.9319639154898138

In [38]:
model3=SVR()
model3.fit(X_train,y_train)

SVR()

In [39]:
y_pred=model3.predict(X_test)
y_pred

array([513.26090499, 199.42698492, 196.41588686, ..., 729.48641925,
       428.84960998, 362.17158064])

In [40]:
mse=mean_squared_error(y_test,y_pred)
mse

26723.170289121754

In [41]:
mae=mean_absolute_error(y_test,y_pred)
mae

131.71845504870157

In [42]:
r2_error=r2_score(y_test,y_pred)
r2_error

0.8123515452438437

In [43]:
model4=RandomForestRegressor()
model4.fit(X_train,y_train)

RandomForestRegressor()

In [44]:
y_pred4=model4.predict(X_test)
y_pred4

array([519.29,  87.13,  32.06, ..., 612.86, 481.25, 305.34])

In [45]:
mse=mean_squared_error(y_test,y_pred4)
mae=mean_absolute_error(y_test,y_pred4)
r2_score=r2_score(y_test,y_pred4)
print('mean_squared_error:',mse)
print('mean_absolute_error:',mae)
print('r2_score:',r2_score)

mean_squared_error: 4612.968086388638
mean_absolute_error: 47.80414493096495
r2_score: 0.9676080224058349


In [46]:
model5=AdaBoostRegressor()
model5.fit(X_train,y_train)

AdaBoostRegressor()

In [47]:
y_pred5=model5.predict(X_test)
y_pred5

array([515.62499341, 186.61714771, 186.61714771, ..., 786.59381339,
       493.51733086, 318.22967444])

In [48]:
mse=mean_squared_error(y_test,y_pred5)
mae=mean_absolute_error(y_test,y_pred5)
print('mean_squared_error:',mse)
print('mean_absolute_error:',mae)

mean_squared_error: 14349.972277495594
mean_absolute_error: 98.1387612572103


In [49]:
r2=r2_score(y_test,y_pred5)
print('R2:',r2)

TypeError: 'float' object is not callable