In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as mlt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.metrics import precision_score, recall_score, f1_score
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("Book_ipl22_ver_33 (1) (1).csv")
df

match_id           date                                         venue  \
0          1  March 26,2022                      Wankhede Stadium, Mumbai   
1          2  March 27,2022                     Brabourne Stadium, Mumbai   
2          3  March 27,2022            Dr DY Patil Sports Academy, Mumbai   
3          4  March 28,2022                      Wankhede Stadium, Mumbai   
4          5  March 29,2022  Maharashtra Cricket Association Stadium,Pune   
..       ...            ...                                           ...   
69        70    May 22,2022                      Wankhede Stadium, Mumbai   
70        71    May 24,2022                         Eden Gardens, Kolkata   
71        72    May 25,2022                         Eden Gardens, Kolkata   
72        73    May 27,2022              Narendra Modi Stadium, Ahmedabad   
73        74    May 29,2022              Narendra Modi Stadium, Ahmedabad   

        team1      team2    stage toss_winner toss_decision  first_ings_score  \
0     Chennai    Kolkata    Group     Kolkata         Field               131   
1       Delhi     Mumbai    Group       Delhi         Field               177   
2    Banglore     Punjab    Group      Punjab         Field               205   
3     Gujarat    Lucknow    Group     Gujarat         Field               158   
4   Hyderabad  Rajasthan    Group   Hyderabad         Field               210   
..        ...        ...      ...         ...           ...               ...   
69  Hyderabad     Punjab    Group   Hyderabad           Bat               157   
70    Gujarat  Rajasthan  Playoff     Gujarat         Field               188   
71   Banglore    Lucknow  Playoff     Lucknow         Field               207   
72   Banglore  Rajasthan  Playoff   Rajasthan         Field               157   
73    Gujarat  Rajasthan    Final   Rajasthan           Bat               130   

    first_ings_wkts  second_ings_score  second_ings_wkts match_winner  \
0                 5                133                 4      Kolkata   
1                 5                179                 6        Delhi   
2                 2                208                 5       Punjab   
3                 6                161                 5      Gujarat   
4                 6                149                 7    Rajasthan   
..              ...                ...               ...          ...   
69                8                160                 5       Punjab   
70                6                191                 3      Gujarat   
71                4                193                 6     Banglore   
72                8                161                 3    Rajasthan   
73                9                133                 3      Gujarat   

     won_by  margin player_of_the_match        top_scorer  highscore  \
0   Wickets       6         Umesh Yadav          MS Dhoni         50   
1   Wickets       4       Kuldeep Yadav      Ishan Kishan         81   
2   Wickets       5         Odean Smith    Faf du Plessis         88   
3   Wickets       5      Mohammed Shami      Deepak Hooda         55   
4      Runs      61        Sanju Samson     Aiden Markram         57   
..      ...     ...                 ...               ...        ...   
69  Wickets       5       Harpreet Brar  Liam Livingstone         49   
70  Wickets       7        David Miller       Jos Buttler         89   
71     Runs      14       Rajat Patidar     Rajat Patidar        112   
72  Wickets       7         Jos Buttler       Jos Buttler        106   
73  Wickets       7       Hardik Pandya      Shubman Gill         45   

        best_bowling best_bowling_figure  
0       Dwayne Bravo               3--20  
1      Kuldeep Yadav               3--18  
2     Mohammed Siraj               2--59  
3     Mohammed Shami               3--25  
4   Yuzvendra Chahal               3--22  
..               ...                 ...  
69     Harpreet Brar               3--26  
70     Hardik Pandya

In [3]:
df.head()

match_id           date                                         venue  \
0         1  March 26,2022                      Wankhede Stadium, Mumbai   
1         2  March 27,2022                     Brabourne Stadium, Mumbai   
2         3  March 27,2022            Dr DY Patil Sports Academy, Mumbai   
3         4  March 28,2022                      Wankhede Stadium, Mumbai   
4         5  March 29,2022  Maharashtra Cricket Association Stadium,Pune   

       team1      team2  stage toss_winner toss_decision  first_ings_score  \
0    Chennai    Kolkata  Group     Kolkata         Field               131   
1      Delhi     Mumbai  Group       Delhi         Field               177   
2   Banglore     Punjab  Group      Punjab         Field               205   
3    Gujarat    Lucknow  Group     Gujarat         Field               158   
4  Hyderabad  Rajasthan  Group   Hyderabad         Field               210   

   first_ings_wkts  second_ings_score  second_ings_wkts match_winner   won_by  \
0                5                133                 4      Kolkata  Wickets   
1                5                179                 6        Delhi  Wickets   
2                2                208                 5       Punjab  Wickets   
3                6                161                 5      Gujarat  Wickets   
4                6                149                 7    Rajasthan     Runs   

   margin player_of_the_match      top_scorer  highscore      best_bowling  \
0       6         Umesh Yadav        MS Dhoni         50      Dwayne Bravo   
1       4       Kuldeep Yadav    Ishan Kishan         81     Kuldeep Yadav   
2       5         Odean Smith  Faf du Plessis         88    Mohammed Siraj   
3       5      Mohammed Shami    Deepak Hooda         55    Mohammed Shami   
4      61        Sanju Samson   Aiden Markram         57  Yuzvendra Chahal   

  best_bowling_figure  
0               3--20  
1               3--18  
2               2--59  
3               3--25  
4               3--22

In [4]:
df.tail()

match_id         date                             venue      team1  \
69        70  May 22,2022          Wankhede Stadium, Mumbai  Hyderabad   
70        71  May 24,2022             Eden Gardens, Kolkata    Gujarat   
71        72  May 25,2022             Eden Gardens, Kolkata   Banglore   
72        73  May 27,2022  Narendra Modi Stadium, Ahmedabad   Banglore   
73        74  May 29,2022  Narendra Modi Stadium, Ahmedabad    Gujarat   

        team2    stage toss_winner toss_decision  first_ings_score  \
69     Punjab    Group   Hyderabad           Bat               157   
70  Rajasthan  Playoff     Gujarat         Field               188   
71    Lucknow  Playoff     Lucknow         Field               207   
72  Rajasthan  Playoff   Rajasthan         Field               157   
73  Rajasthan    Final   Rajasthan           Bat               130   

    first_ings_wkts  second_ings_score  second_ings_wkts match_winner  \
69                8                160                 5       Punjab   
70                6                191                 3      Gujarat   
71                4                193                 6     Banglore   
72                8                161                 3    Rajasthan   
73                9                133                 3      Gujarat   

     won_by  margin player_of_the_match        top_scorer  highscore  \
69  Wickets       5       Harpreet Brar  Liam Livingstone         49   
70  Wickets       7        David Miller       Jos Buttler         89   
71     Runs      14       Rajat Patidar     Rajat Patidar        112   
72  Wickets       7         Jos Buttler       Jos Buttler        106   
73  Wickets       7       Hardik Pandya      Shubman Gill         45   

       best_bowling best_bowling_figure  
69    Harpreet Brar               3--26  
70    Hardik Pandya               1--14  
71   Josh Hazlewood               3--43  
72  Prasidh Krishna               3--22  
73    Hardik Pandya               3--17

In [5]:
df.shape

(74, 20)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   match_id             74 non-null     int64 
 1   date                 74 non-null     object
 2   venue                74 non-null     object
 3   team1                74 non-null     object
 4   team2                74 non-null     object
 5   stage                74 non-null     object
 6   toss_winner          74 non-null     object
 7   toss_decision        74 non-null     object
 8   first_ings_score     74 non-null     int64 
 9   first_ings_wkts      74 non-null     int64 
 10  second_ings_score    74 non-null     int64 
 11  second_ings_wkts     74 non-null     int64 
 12  match_winner         74 non-null     object
 13  won_by               74 non-null     object
 14  margin               74 non-null     int64 
 15  player_of_the_match  74 non-null     object
 16  top_scorer

In [7]:
df.dtypes

match_id                int64
date                   object
venue                  object
team1                  object
team2                  object
stage                  object
toss_winner            object
toss_decision          object
first_ings_score        int64
first_ings_wkts         int64
second_ings_score       int64
second_ings_wkts        int64
match_winner           object
won_by                 object
margin                  int64
player_of_the_match    object
top_scorer             object
highscore               int64
best_bowling           object
best_bowling_figure    object
dtype: object

In [8]:
df.describe()

match_id  first_ings_score  first_ings_wkts  second_ings_score  \
count  74.000000         74.000000        74.000000          74.000000   
mean   37.500000        171.121622         6.135135         158.540541   
std    21.505813         29.048355         2.222699          29.299207   
min     1.000000         68.000000         0.000000          72.000000   
25%    19.250000        154.250000         5.000000         142.750000   
50%    37.500000        169.500000         6.000000         160.000000   
75%    55.750000        192.750000         8.000000         176.000000   
max    74.000000        222.000000        10.000000         211.000000   

       second_ings_wkts     margin   highscore  
count         74.000000  74.000000   74.000000  
mean           6.175676  16.972973   71.716216  
std            2.639832  19.651047   20.705052  
min            1.000000   2.000000   28.000000  
25%            4.000000   5.250000   57.000000  
50%            6.000000   8.000000   68.000000  
75%            8.000000  18.000000   87.750000  
max           10.000000  91.000000  140.000000

In [9]:
df.isnull().sum()

match_id               0
date                   0
venue                  0
team1                  0
team2                  0
stage                  0
toss_winner            0
toss_decision          0
first_ings_score       0
first_ings_wkts        0
second_ings_score      0
second_ings_wkts       0
match_winner           0
won_by                 0
margin                 0
player_of_the_match    0
top_scorer             0
highscore              0
best_bowling           0
best_bowling_figure    0
dtype: int64

In [10]:
le=LabelEncoder()

In [11]:
for column in df.columns:
    if df[column].dtypes=='object':
        df[column]=le.fit_transform(df[column])

In [12]:
df.dtypes

match_id               int64
date                   int32
venue                  int32
team1                  int32
team2                  int32
stage                  int32
toss_winner            int32
toss_decision          int32
first_ings_score       int64
first_ings_wkts        int64
second_ings_score      int64
second_ings_wkts       int64
match_winner           int32
won_by                 int32
margin                 int64
player_of_the_match    int32
top_scorer             int32
highscore              int64
best_bowling           int32
best_bowling_figure    int32
dtype: object

In [13]:
df

match_id  date  venue  team1  team2  stage  toss_winner  toss_decision  \
0          1    30      5      1      4      1            5              1   
1          2    31      0      2      6      1            2              1   
2          3    31      1      0      7      1            8              1   
3          4    32      5      3      5      1            3              1   
4          5    33      3      4      8      1            4              1   
..       ...   ...    ...    ...    ...    ...          ...            ...   
69        70    50      5      4      7      1            4              0   
70        71    51      2      3      8      2            3              1   
71        72    52      2      0      5      2            6              1   
72        73    53      4      0      8      2            9              1   
73        74    54      4      3      8      0            9              0   

    first_ings_score  first_ings_wkts  second_ings_score  second_ings_wkts  \
0                131                5                133                 4   
1                177                5                179                 6   
2                205                2                208                 5   
3                158                6                161                 5   
4                210                6                149                 7   
..               ...              ...                ...               ...   
69               157                8                160                 5   
70               188                6                191                 3   
71               207                4                193                 6   
72               157                8                161                 3   
73               130                9                133                 3   

    match_winner  won_by  margin  player_of_the_match  top_scorer  highscore  \
0              5       1       6                   49          15         50   
1              2       1       4                   21          10         81   
2              8       1       5                   30           8         88   
3              3       1       5                   27           5         55   
4              9       0      61                   41           1         57   
..           ...     ...     ...                  ...         ...        ...   
69             8       1       5                   12          14         49   
70             3       1       7                    5          11         89   
71             0       0      14                   36          22        112   
72             9       1       7                   16          11        106   
73             3       1       7                   11          31         45   

    best_bowling  best_bowling_figure  
0              5                   21  
1             15                   19  
2             20                   14  
3             19                   24  
4             41                   22  
..           ...                  ...  
69             7                   25  
70             6                    0  
71            10                   30  
72            27                   22  
73             6                   18  

[74 rows x 20 columns]

In [14]:
X=df.drop(columns='best_bowling')
Y=df['best_bowling']
X_train,X_test,Y_train,Y_test= train_test_split(X,Y,test_size=0.2,random_state=42)

## logistic regression

In [16]:
model1=LogisticRegression()
model1.fit(X_train,Y_train)

LogisticRegression()

In [17]:
Y_pred1=model1.predict(X_test)
Y_pred1

array([30, 14, 16, 19, 27,  4, 16, 38, 40,  1, 27, 34,  1, 17, 41])

In [18]:
precision = precision_score(Y_test, Y_pred1,average='weighted')
recall = recall_score(Y_test, Y_pred1,average='weighted')
f1 = f1_score(Y_test, Y_pred1,average='weighted')
accuracy = accuracy_score(Y_test, Y_pred1)

print("Precision:", precision)
print("Recall (Sensitivity):", recall)
print("F1 Score:",f1)
print("accuracy:",accuracy)

Precision: 0.0
Recall (Sensitivity): 0.0
F1 Score: 0.0
accuracy: 0.0


In [19]:
cm = confusion_matrix(Y_test, Y_pred1)
cm

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [20]:
report = classification_report(Y_test, Y_pred1)
print(report)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           1       0.00      0.00      0.00       0.0
           2       0.00      0.00      0.00       1.0
           4       0.00      0.00      0.00       0.0
           5       0.00      0.00      0.00       2.0
           6       0.00      0.00      0.00       1.0
           9       0.00      0.00      0.00       1.0
          14       0.00      0.00      0.00       0.0
          15       0.00      0.00      0.00       1.0
          16       0.00      0.00      0.00       1.0
          17       0.00      0.00      0.00       0.0
          19       0.00      0.00      0.00       0.0
          21       0.00      0.00      0.00       1.0
          22       0.00      0.00      0.00       1.0
          27       0.00      0.00      0.00       0.0
          28       0.00      0.00      0.00       1.0
          30       0.00      0.00      0.00       0.0
          33       0.00    

## DECISION TREE CLASSIFIER

In [22]:
model2=DecisionTreeClassifier()
model2.fit(X_train,Y_train)

DecisionTreeClassifier()

In [23]:
Y_pred2=model2.predict(X_test)
Y_pred2

array([ 9, 14, 17, 36,  4, 34,  8, 11,  8,  1, 27, 34, 14, 11, 19])

In [24]:
precision = precision_score(Y_test, Y_pred2,average='weighted')
recall = recall_score(Y_test, Y_pred2,average='weighted')
f1 = f1_score(Y_test, Y_pred2,average='weighted')
accuracy = accuracy_score(Y_test, Y_pred2)

print("Precision:", precision)
print("Recall (Sensitivity):", recall)
print("F1 Score:",f1)
print("accuracy:",accuracy)

Precision: 0.0
Recall (Sensitivity): 0.0
F1 Score: 0.0
accuracy: 0.0


In [25]:
cm = confusion_matrix(Y_test, Y_pred2)
cm

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0

In [26]:
report = classification_report(Y_test, Y_pred2)
print(report)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           1       0.00      0.00      0.00       0.0
           2       0.00      0.00      0.00       1.0
           4       0.00      0.00      0.00       0.0
           5       0.00      0.00      0.00       2.0
           6       0.00      0.00      0.00       1.0
           8       0.00      0.00      0.00       0.0
           9       0.00      0.00      0.00       1.0
          11       0.00      0.00      0.00       0.0
          14       0.00      0.00      0.00       0.0
          15       0.00      0.00      0.00       1.0
          16       0.00      0.00      0.00       1.0
          17       0.00      0.00      0.00       0.0
          19       0.00      0.00      0.00       0.0
          21       0.00      0.00      0.00       1.0
          22       0.00      0.00      0.00       1.0
          27       0.00      0.00      0.00       0.0
          28       0.00    

## SVM

In [28]:
model3=SVC()
model3.fit(X_train,Y_train)

SVC()

In [29]:
Y_pred3=model3.predict(X_test)
Y_pred3

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30])

In [30]:
precision = precision_score(Y_test, Y_pred3,average='weighted')
recall = recall_score(Y_test, Y_pred3,average='weighted')
f1 = f1_score(Y_test, Y_pred3,average='weighted')
accuracy = accuracy_score(Y_test, Y_pred3)

print("Precision:", precision)
print("Recall (Sensitivity):", recall)
print("F1 Score:",f1)
print("accuracy:",accuracy)

Precision: 0.0
Recall (Sensitivity): 0.0
F1 Score: 0.0
accuracy: 0.0


In [31]:
cm = confusion_matrix(Y_test, Y_pred3)
cm

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0]], dtype=int64)

In [32]:
report = classification_report(Y_test, Y_pred3)
print(report)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           2       0.00      0.00      0.00       1.0
           5       0.00      0.00      0.00       2.0
           6       0.00      0.00      0.00       1.0
           9       0.00      0.00      0.00       1.0
          15       0.00      0.00      0.00       1.0
          16       0.00      0.00      0.00       1.0
          21       0.00      0.00      0.00       1.0
          22       0.00      0.00      0.00       1.0
          28       0.00      0.00      0.00       1.0
          30       0.00      0.00      0.00       0.0
          33       0.00      0.00      0.00       1.0
          39       0.00      0.00      0.00       1.0
          41       0.00      0.00      0.00       2.0

    accuracy                           0.00      15.0
   macro avg       0.00      0.00      0.00      15.0
weighted avg       0.00      0.00      0.00      15.0



## RANDOM FOREST CLASSIFIER

In [34]:
model4=RandomForestClassifier()
model4.fit(X_train,Y_train)

RandomForestClassifier()

In [35]:
Y_pred4=model4.predict(X_test)
Y_pred4

array([ 9, 11, 12, 19, 15,  7,  1, 11,  8,  1, 21, 34, 30, 10,  4])

In [36]:
precision4 = precision_score(Y_test, Y_pred4,average='weighted')
recall4 = recall_score(Y_test, Y_pred4,average='weighted')
f14 = f1_score(Y_test, Y_pred4,average='weighted')
accuracy4 = accuracy_score(Y_test, Y_pred4)

print("Precision:", precision4)
print("Recall (Sensitivity):", recall4)
print("F1 Score:",f14)
print("accuracy:",accuracy4)

Precision: 0.06666666666666667
Recall (Sensitivity): 0.06666666666666667
F1 Score: 0.06666666666666667
accuracy: 0.06666666666666667


In [37]:
cm = confusion_matrix(Y_test, Y_pred4)
cm

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [38]:
report = classification_report(Y_test, Y_pred4)
print(report)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         0
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         0
           8       0.00      0.00      0.00         0
           9       0.00      0.00      0.00         1
          10       0.00      0.00      0.00         0
          11       0.00      0.00      0.00         0
          12       0.00      0.00      0.00         0
          15       0.00      0.00      0.00         1
          16       0.00      0.00      0.00         1
          19       0.00      0.00      0.00         0
          21       1.00      1.00      1.00         1
          22       0.00      0.00      0.00         1
          28       0.00    

## XGBOOST

In [40]:
le = LabelEncoder()
le.fit(Y_train)
Y_train_encoded = le.transform(Y_train)

model5 = XGBClassifier()
model5.fit(X_train, Y_train_encoded)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [41]:
Y_pred5=model5.predict(X_test)
Y_pred5

array([31, 31, 29,  3, 13, 17,  1, 17, 13,  1, 24, 29, 26,  8,  3],
      dtype=int64)

In [42]:
precision = precision_score(Y_test, Y_pred5,average='weighted')
recall = recall_score(Y_test, Y_pred5,average='weighted')
f1 = f1_score(Y_test, Y_pred5,average='weighted')
accuracy = accuracy_score(Y_test, Y_pred5)

print("Precision:", precision)
print("Recall (Sensitivity):", recall)
print("F1 Score:",f1)
print("accuracy:",accuracy)

Precision: 0.0
Recall (Sensitivity): 0.0
F1 Score: 0.0
accuracy: 0.0


In [43]:
cm = confusion_matrix(Y_test, Y_pred5)
cm

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0,

In [44]:
report = classification_report(Y_test, Y_pred5)
print(report)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           1       0.00      0.00      0.00       0.0
           2       0.00      0.00      0.00       1.0
           3       0.00      0.00      0.00       0.0
           5       0.00      0.00      0.00       2.0
           6       0.00      0.00      0.00       1.0
           8       0.00      0.00      0.00       0.0
           9       0.00      0.00      0.00       1.0
          13       0.00      0.00      0.00       0.0
          15       0.00      0.00      0.00       1.0
          16       0.00      0.00      0.00       1.0
          17       0.00      0.00      0.00       0.0
          21       0.00      0.00      0.00       1.0
          22       0.00      0.00      0.00       1.0
          24       0.00      0.00      0.00       0.0
          26       0.00      0.00      0.00       0.0
          28       0.00      0.00      0.00       1.0
          29       0.00    